### PR TITLE
add html output for linting service

### PR DESCRIPTION
**Pull request by ltankey**

### CODE REVIEW

**Comment by tessereth** [comment]
Looks good but did you figure out how to make the default format json or is it still html? Can you add a test for the default format?

**Comment by ltankey** [comment]
Yeah, "default" in this context is with no format extension specified in the URL, i.e. `/foo` vs. `/foo.html`

Works now and have implemented tests for both cases :+1:

**Comment by tessereth** [comment]
But as far as I can tell there's no test for providing content but not specifying the format

**Comment by ltankey** [comment]
Ahh gotchya, my head was stuck in URL routing (where the default is in the URL suffix).

Let me add one for the controller and commit

**Comment by ltankey** [comment]
OK so I don't think this will be possible to demonstrate via Rspec: https://github.com/rspec/rspec-rails/issues/900

For now, I'll leave the test out as it does not improve coverage and is not an explicit requirement/behaviour.

**Comment by tessereth** [comment]
Makes sense.

**Pull request merged**
